package application;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;

public class SampleController {
	
	@FXML
	private Button btn1;
	@FXML
	private TextArea result;
//	@FXML
//	private TextField edad;
	@FXML
	private TextField apellido;
	@FXML
	private TextField nombre;

	// Event Listener on Button[#btn1].onAction
	@FXML
	public void click(ActionEvent event) {
		// TODO Autogenerated
		
		result.setText("Hola " + nombre.getText().toString() + " " + apellido.getText().toString());
		
	}
	
}
